git:
  depth: 5

language: node_js
node_js: 6

before_install:
- npm config set spin false --global

cache:
  directories:
  - ~/.npm

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master

env:
  global:
  - secure: aZNSHHt/4yEfzPl+L2Q+A7USvwjklv2/3Tyd+w3zipqlTiZDSNeqA0vuiKUvHY0XE/cs54v/1sb0CYopB4lDCRTAH6cB7qi7qaSlBg1wcfs5DhKwPWQC2pJrXmnaUVnVrYlzqcZ1RcpK7AxlUw4QIeMUCDGCkSVCLTYogWPXNYY=
